-- require("copilot").setup {
--   suggestion = {
--     auto_trigger = true,
--     keymap = {
--       -- alt + j
--       accept = "∆",
--       -- alt + l
--       accept_line = "¬",
--       -- alt + k
--       accept_word = "˚",
--       -- alt + ]
--       next = "‘",
--       -- alt + [
--       prev = "“",
--       -- alt + c
--       dismiss = "ç",
--     }
--   }
-- }
